// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvOOj1WmzeXCdncBMcjLNydnq0wyvNlq8',
    appId: '1:214860244237:web:06478d17beded02307bc44',
    messagingSenderId: '214860244237',
    projectId: 'nti3-f80c4',
    authDomain: 'nti3-f80c4.firebaseapp.com',
    storageBucket: 'nti3-f80c4.firebasestorage.app',
    measurementId: 'G-CHGTBKW4W2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaURIH3bi9IATq9HPjMP8yc0l47_53lfw',
    appId: '1:214860244237:android:a8943b9a785008c507bc44',
    messagingSenderId: '214860244237',
    projectId: 'nti3-f80c4',
    storageBucket: 'nti3-f80c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFlZkIaBIEyJxG2_cToxz_LiaQTBWmD1g',
    appId: '1:214860244237:ios:b5369f5a2c920c5a07bc44',
    messagingSenderId: '214860244237',
    projectId: 'nti3-f80c4',
    storageBucket: 'nti3-f80c4.firebasestorage.app',
    iosBundleId: 'com.example.nti3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFlZkIaBIEyJxG2_cToxz_LiaQTBWmD1g',
    appId: '1:214860244237:ios:b5369f5a2c920c5a07bc44',
    messagingSenderId: '214860244237',
    projectId: 'nti3-f80c4',
    storageBucket: 'nti3-f80c4.firebasestorage.app',
    iosBundleId: 'com.example.nti3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvOOj1WmzeXCdncBMcjLNydnq0wyvNlq8',
    appId: '1:214860244237:web:13d695b80344c2e807bc44',
    messagingSenderId: '214860244237',
    projectId: 'nti3-f80c4',
    authDomain: 'nti3-f80c4.firebaseapp.com',
    storageBucket: 'nti3-f80c4.firebasestorage.app',
    measurementId: 'G-N519GJD3LW',
  );
}
