// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMVInFU_iJ96H2gwEPDPpCqfSczAhryU',
    appId: '1:665858257582:web:826553a24fce142e57b33f',
    messagingSenderId: '665858257582',
    projectId: 'nti3-e757a',
    authDomain: 'nti3-e757a.firebaseapp.com',
    storageBucket: 'nti3-e757a.firebasestorage.app',
    measurementId: 'G-LGJES84JSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIa2_HnOvEtULf0uXqT4fOMpctvEWfY5w',
    appId: '1:665858257582:android:dd99b6e95b4d519457b33f',
    messagingSenderId: '665858257582',
    projectId: 'nti3-e757a',
    storageBucket: 'nti3-e757a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1hX1Q4scmZs6W09fTJ7ucDexgu5Ds224',
    appId: '1:665858257582:ios:a12a032502d2a42b57b33f',
    messagingSenderId: '665858257582',
    projectId: 'nti3-e757a',
    storageBucket: 'nti3-e757a.firebasestorage.app',
    iosBundleId: 'com.example.nti3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1hX1Q4scmZs6W09fTJ7ucDexgu5Ds224',
    appId: '1:665858257582:ios:a12a032502d2a42b57b33f',
    messagingSenderId: '665858257582',
    projectId: 'nti3-e757a',
    storageBucket: 'nti3-e757a.firebasestorage.app',
    iosBundleId: 'com.example.nti3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiMVInFU_iJ96H2gwEPDPpCqfSczAhryU',
    appId: '1:665858257582:web:5eac9e36d80ba77c57b33f',
    messagingSenderId: '665858257582',
    projectId: 'nti3-e757a',
    authDomain: 'nti3-e757a.firebaseapp.com',
    storageBucket: 'nti3-e757a.firebasestorage.app',
    measurementId: 'G-7B01K12MKR',
  );
}
